import json
import re
from pathlib import Path

from app.config import PROJECTS_DIR


def slugify(value: str, fallback: str = "generated_app") -> str:
    value = re.sub(r"[^a-zA-Z0-9]+", "_", value.lower()).strip("_")
    return value[:60] or fallback


def infer_project_slug(prompt: str) -> str:
    lowered = prompt.lower()
    if "bank" in lowered:
        return "banking_application"
    if "todo" in lowered or "task" in lowered:
        return "task_manager"
    words = re.findall(r"[a-zA-Z0-9]+", prompt.lower())
    useful = [word for word in words if word not in {"create", "make", "build", "an", "a", "the", "application", "app"}]
    return slugify("_".join(useful[:4]), "generated_app")


def next_available_project_dir(slug: str) -> Path:
    project_dir = PROJECTS_DIR / slug
    if not project_dir.exists():
        return project_dir

    index = 2
    while True:
        candidate = PROJECTS_DIR / f"{slug}_{index}"
        if not candidate.exists():
            return candidate
        index += 1


def banking_app_files(prompt: str) -> dict[str, str]:
    app_code = '''import sys
from pathlib import Path

import pandas as pd
import streamlit as st


ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.banking_store import get_account, load_data, record_transaction, save_data


st.set_page_config(page_title="Banking Application", layout="wide")
st.title("Banking Application")
st.caption("A local banking dashboard generated by the agent.")

data = load_data()

total_balance = sum(account["balance"] for account in data["accounts"])
col_customers, col_accounts, col_balance = st.columns(3)
col_customers.metric("Customers", len(data["customers"]))
col_accounts.metric("Accounts", len(data["accounts"]))
col_balance.metric("Total Balance", f"Rs. {total_balance:,.2f}")

tab_overview, tab_transactions, tab_customers = st.tabs(["Overview", "Transactions", "Customers"])

with tab_overview:
    st.subheader("Accounts")
    account_rows = []
    customers = {customer["id"]: customer for customer in data["customers"]}
    for account in data["accounts"]:
        customer = customers.get(account["customer_id"], {})
        account_rows.append({**account, "customer_name": customer.get("name", "Unknown")})
    st.dataframe(pd.DataFrame(account_rows), use_container_width=True, hide_index=True)

with tab_transactions:
    st.subheader("Create Transaction")
    account_no = st.selectbox("Account", [account["account_no"] for account in data["accounts"]])
    kind = st.radio("Type", ["deposit", "withdrawal"], horizontal=True)
    amount = st.number_input("Amount", min_value=1.0, step=500.0)
    note = st.text_input("Note", value="Manual transaction")

    if st.button("Post Transaction", type="primary"):
        account = get_account(data, account_no)
        if not account:
            st.error("Account not found.")
        elif kind == "withdrawal" and account["balance"] < amount:
            st.error("Insufficient balance.")
        else:
            account["balance"] += amount if kind == "deposit" else -amount
            record_transaction(data, account_no, kind, amount, note)
            save_data(data)
            st.success("Transaction posted.")
            st.rerun()

    st.subheader("Ledger")
    st.dataframe(pd.DataFrame(data["transactions"]), use_container_width=True, hide_index=True)

with tab_customers:
    st.subheader("Add Customer")
    with st.form("customer_form"):
        name = st.text_input("Name")
        email = st.text_input("Email")
        submitted = st.form_submit_button("Create Customer")
    if submitted:
        next_id = f"CUST-{1001 + len(data['customers'])}"
        data["customers"].append({"id": next_id, "name": name, "email": email})
        save_data(data)
        st.success(f"Customer {next_id} created.")
        st.rerun()

    st.dataframe(pd.DataFrame(data["customers"]), use_container_width=True, hide_index=True)
'''

    store_code = '''import json
from datetime import datetime
from pathlib import Path


DATA_FILE = Path("data") / "banking_data.json"


def default_data() -> dict:
    return {
        "customers": [
            {"id": "CUST-1001", "name": "Asha Patel", "email": "asha@example.com"},
            {"id": "CUST-1002", "name": "Rahul Sharma", "email": "rahul@example.com"},
        ],
        "accounts": [
            {"account_no": "AC-90001", "customer_id": "CUST-1001", "type": "Savings", "balance": 125000.0},
            {"account_no": "AC-90002", "customer_id": "CUST-1002", "type": "Current", "balance": 68000.0},
        ],
        "transactions": [
            {
                "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "account_no": "AC-90001",
                "kind": "deposit",
                "amount": 25000.0,
                "note": "Opening deposit",
            }
        ],
    }


def load_data() -> dict:
    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    if not DATA_FILE.exists():
        save_data(default_data())
    return json.loads(DATA_FILE.read_text(encoding="utf-8"))


def save_data(data: dict) -> None:
    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    DATA_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")


def get_account(data: dict, account_no: str) -> dict | None:
    return next((account for account in data["accounts"] if account["account_no"] == account_no), None)


def record_transaction(data: dict, account_no: str, kind: str, amount: float, note: str) -> None:
    data["transactions"].append(
        {
            "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "account_no": account_no,
            "kind": kind,
            "amount": amount,
            "note": note,
        }
    )
'''

    readme = f'''# Banking Application

This project was generated from the prompt:

> {prompt}

## What It Does

The app is a local Streamlit banking dashboard. It manages demo customers,
accounts, balances, deposits, withdrawals, and a simple transaction ledger.

## Files

- `app.py` contains the Streamlit UI.
- `src/banking_store.py` contains local data and transaction helpers.
- `data/banking_data.json` is created automatically on first run and stores local demo data.
- `docs/ARCHITECTURE.md` explains the generated app layout.
- `requirements.txt` lists the Python packages needed by the project.
- `.vscode/tasks.json` gives VS Code setup and run tasks.

## Run

```powershell
python -m pip install -r requirements.txt
streamlit run app.py
```

The app stores data locally in this project folder. It is a demo scaffold, not
production banking software.
'''

    vscode_tasks = {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "Install dependencies",
                "type": "shell",
                "command": "python -m pip install -r requirements.txt",
                "problemMatcher": [],
            },
            {
                "label": "Run app",
                "type": "shell",
                "command": "streamlit run app.py",
                "problemMatcher": [],
                "dependsOn": "Install dependencies",
            },
        ],
    }

    return {
        "app.py": app_code,
        "src/__init__.py": "",
        "src/banking_store.py": store_code,
        "data/.gitkeep": "",
        "docs/ARCHITECTURE.md": "# Architecture\n\nThe generated banking app keeps UI code in `app.py`, reusable data helpers in `src/`, local runtime data in `data/`, and IDE commands in `.vscode/tasks.json`.\n",
        "requirements.txt": "streamlit>=1.35\npandas>=2.0\n",
        ".gitignore": "__pycache__/\n*.pyc\ndata/*.json\n.venv/\n",
        ".streamlit/config.toml": "[theme]\nbase = \"light\"\n",
        "README.md": readme,
        ".vscode/tasks.json": json.dumps(vscode_tasks, indent=2),
    }


def generic_app_files(prompt: str) -> dict[str, str]:
    title = prompt.strip().rstrip(".") or "Generated Application"
    app_code = f'''import sys
from pathlib import Path

import streamlit as st


ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.app_logic import normalize_item


st.set_page_config(page_title="{title}", layout="wide")
st.title("{title}")
st.write("This generated app is ready for you to extend.")

with st.form("demo_form"):
    item = st.text_input("Item")
    submitted = st.form_submit_button("Save")

if submitted and item:
    st.success(f"Saved: {{normalize_item(item)}}")
'''
    logic_code = '''def normalize_item(value: str) -> str:
    return value.strip()
'''
    readme = f'''# {title}

Generated from:

> {prompt}

## What It Does

This is a Streamlit starter application created by the local automation agent.
It includes a runnable UI and a place to extend the workflow.

## Run

```powershell
python -m pip install -r requirements.txt
streamlit run app.py
```
'''
    return {
        "app.py": app_code,
        "src/__init__.py": "",
        "src/app_logic.py": logic_code,
        "docs/ARCHITECTURE.md": "# Architecture\n\nThe generated app keeps UI code in `app.py`, reusable logic in `src/`, and IDE commands in `.vscode/tasks.json`.\n",
        "requirements.txt": "streamlit>=1.35\n",
        ".gitignore": "__pycache__/\n*.pyc\n.venv/\n",
        ".streamlit/config.toml": "[theme]\nbase = \"light\"\n",
        "README.md": readme,
        ".vscode/tasks.json": json.dumps(
            {
                "version": "2.0.0",
                "tasks": [
                    {"label": "Install dependencies", "type": "shell", "command": "python -m pip install -r requirements.txt", "problemMatcher": []},
                    {"label": "Run app", "type": "shell", "command": "streamlit run app.py", "problemMatcher": [], "dependsOn": "Install dependencies"},
                ],
            },
            indent=2,
        ),
    }


def generate_project(prompt: str, owner: str = "local_user") -> dict:
    slug = infer_project_slug(prompt)
    project_dir = next_available_project_dir(slug)
    actual_slug = project_dir.name
    project_dir.mkdir(parents=True, exist_ok=True)

    files = banking_app_files(prompt) if "bank" in prompt.lower() else generic_app_files(prompt)
    written = []
    for relative_path, contents in files.items():
        target = project_dir / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(contents, encoding="utf-8")
        written.append(relative_path)

    manifest = {
        "project": actual_slug,
        "owner": owner,
        "prompt": prompt,
        "path": str(project_dir),
        "workspace_path": f"generated_projects/{actual_slug}",
        "command_cwd": actual_slug,
        "files": written,
        "setup_command": "python -m pip install -r requirements.txt",
        "run_command": "streamlit run app.py",
    }
    (project_dir / "agent_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest
