import sys
from pathlib import Path

import pandas as pd
import streamlit as st


ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.banking_store import get_account, load_data, record_transaction, save_data


st.set_page_config(page_title="Banking Application", layout="wide")
st.title("Banking Application")
st.caption("A local banking dashboard generated by the agent.")

data = load_data()

total_balance = sum(account["balance"] for account in data["accounts"])
col_customers, col_accounts, col_balance = st.columns(3)
col_customers.metric("Customers", len(data["customers"]))
col_accounts.metric("Accounts", len(data["accounts"]))
col_balance.metric("Total Balance", f"Rs. {total_balance:,.2f}")

tab_overview, tab_transactions, tab_customers = st.tabs(["Overview", "Transactions", "Customers"])

with tab_overview:
    st.subheader("Accounts")
    account_rows = []
    customers = {customer["id"]: customer for customer in data["customers"]}
    for account in data["accounts"]:
        customer = customers.get(account["customer_id"], {})
        account_rows.append({**account, "customer_name": customer.get("name", "Unknown")})
    st.dataframe(pd.DataFrame(account_rows), use_container_width=True, hide_index=True)

with tab_transactions:
    st.subheader("Create Transaction")
    account_no = st.selectbox("Account", [account["account_no"] for account in data["accounts"]])
    kind = st.radio("Type", ["deposit", "withdrawal"], horizontal=True)
    amount = st.number_input("Amount", min_value=1.0, step=500.0)
    note = st.text_input("Note", value="Manual transaction")

    if st.button("Post Transaction", type="primary"):
        account = get_account(data, account_no)
        if not account:
            st.error("Account not found.")
        elif kind == "withdrawal" and account["balance"] < amount:
            st.error("Insufficient balance.")
        else:
            account["balance"] += amount if kind == "deposit" else -amount
            record_transaction(data, account_no, kind, amount, note)
            save_data(data)
            st.success("Transaction posted.")
            st.rerun()

    st.subheader("Ledger")
    st.dataframe(pd.DataFrame(data["transactions"]), use_container_width=True, hide_index=True)

with tab_customers:
    st.subheader("Add Customer")
    with st.form("customer_form"):
        name = st.text_input("Name")
        email = st.text_input("Email")
        submitted = st.form_submit_button("Create Customer")
    if submitted:
        next_id = f"CUST-{1001 + len(data['customers'])}"
        data["customers"].append({"id": next_id, "name": name, "email": email})
        save_data(data)
        st.success(f"Customer {next_id} created.")
        st.rerun()

    st.dataframe(pd.DataFrame(data["customers"]), use_container_width=True, hide_index=True)
